language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_script:
  - git clone git://github.com/phalcon/cphalcon.git --depth=1 && cd cphalcon && git checkout 1.3.4 && cd build && sudo ./install
  - cd ../../ && phpenv config-add ./tests/phalcon.ini
  - composer self-update
  - composer install
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
script:
  phpunit -v &
  phpcs --standard=PSR2 --extensions=php --ignore=vendor/*,tests/*,cphalcon/* --warning-severity=0 ./