language: php
php:
  - 5.3
  - 5.4
  - 5.5
before_script:
  - git clone git://github.com/phalcon/cphalcon.git --depth=1 && cd cphalcon/build/safe && phpize && ./configure --enable-phalcon && sudo make install
  - cd ../../../ && phpenv config-add ./tests/phalcon.ini
  - composer self-update
  - composer install
script:
  phpunit -v &
  phpcs --standard=PSR2 --extensions=php --ignore=vendor/*,tests/* ./